// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package layout

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// Now renders the site-wide status strip that sits sticky beneath the nav.
// Editable in one place; appears on every page via Base.
func Now() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"sticky top-14 z-20 border-b border-bg-border bg-bg/85 backdrop-blur supports-[backdrop-filter]:bg-bg/70\"><div class=\"w-full max-w-5xl mx-auto px-4 py-2.5\"><div class=\"flex flex-wrap items-center gap-x-4 gap-y-1 text-xs\"><span class=\"font-mono text-[10px] text-accent uppercase tracking-[0.22em]\">Now</span> <span class=\"text-text-muted\">Building <span class=\"text-text\">Beetl Bot</span></span> <span class=\"text-text-muted/40\">·</span> <span class=\"text-text-muted\">On a mountain in <span class=\"text-text\">Colombia</span></span> <span class=\"text-text-muted/40\">·</span> <span class=\"text-accent-2\">Open for new work</span></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
